### ISSUE TITLE
[MEM-60] [BUG] Code blocks containing markdown do not appear

### ISSUE THREAD

**Issue by bakavic** [Memmy-App/memmy#141]
**Describe the bug**
If a code block contains Markdown, the code is not displayed, and a blank code block is shown.

Only markdown is affected, other code text renders correctly.

**To Reproduce**

1. Create a new post, and add a code block using 3 backticks (\`\`\`)
2. Add markdown code in the code block
3. Submit post
4. Post renders as a blank code block in memmy, but renders correctly in lemmy-ui.

Example post: [https://lemmy.ml/post/1505127](https://lemmy.ml/post/1505127)

Discovered in this post:
[https://lemmy.world/post/561800](https://lemmy.world/post/561800)

**Expected behavior**
Markdown code in a code block should show in its unparsed form.

**Screenshots**

![](https://uploads.linear.app/7655b776-38c4-4273-b069-78045fe3cd9c/18cd728b-25aa-4546-b613-8725cd92a745/14435481-c2f8-40f0-bf59-f92e59fa1e2b)

![](https://uploads.linear.app/7655b776-38c4-4273-b069-78045fe3cd9c/e9647737-f0c5-4c8e-803b-39c86b9adace/4b8742d0-e90c-4416-90a8-92d8e66deae1)

**Smartphone (please complete the following information):**

* Device: iPhone 12 mini
* OS: iOS 16.5.1
* Version: 65

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-60](https://linear.app/memmyapp/issue/MEM-60/[bug]-code-blocks-containing-markdown-do-not-appear)</sub>

**Comment by yrahul3910** [comment]
This is most likely due to [images being disabled](https://github.com/gkasdorf/memmy/blob/main/components/ui/markdown/RenderMarkdown.tsx#L189) in Markdown rendering. Therefore, code blocks (which are Markdown syntax) are still rendered using the `<Markdown>` component, and in turn, if that code contains Markdown for an image specifically, that won't be displayed. I wonder if this is something to bring up with [the library](https://github.com/iamacup/react-native-markdown-display) or something to do ourselves.
