### ISSUE TITLE
[MEM-71] Hide viewed posts

### ISSUE THREAD

**Issue by grosejon** [Memmy-App/memmy#149]
**Is your feature request related to a problem? Please describe.**
No, it's my favorite feature from Apollo. 

**Describe the solution you'd like**
I would love an option to be able to hide posts that I have already viewed. This was something in Apollo and I absolutely loved it. 

**Describe alternatives you've considered**
Nothing?

**Additional context**
None

<sub>[MEM-71](https://linear.app/memmyapp/issue/MEM-71/hide-viewed-posts)</sub>

**Comment by graham-pyett** [comment]
Just to add on I have some further suggestions related to this.

The best situation IMO is that when you look at a post it's marked "read" and the title is greyed out when you look at the list of posts. Then, when you refresh the feed read posts would be hidden. Apollo also had the option to auto-mark posts read as you scrolled past them, but personally I never used that.

I know Lemmy as a whole has a setting to hide read posts, but it seems like it's way to strong. You can't even see your own submissions on your profile page if it's enabled, since you've "read" those.

Finally, I'll suggest that there should be an option to not hide read posts if you're specifically looking at a given community. I often try to find things I've seen before by going to the community and I want to see the read posts there. So a setting to hide read posts only on the main feeds would be excellent

**Comment by gkasdorf** [comment]
Marking them as read is done.

What I'll do in the future here soon is actually make a sort option, "Unread". If you are using that option, once you view a post it will disappear.

**Comment by teddyursa** [comment]
Looking forward to this being implemented. It will be the sole feature to get me to 'mainline' your app. I loved scrolling past stuff on Apollo and just having a fresh feed each time. Keep up the good work dude!

**Comment by gkasdorf** [comment]
Going to bump this because there's a lot of interest and I think we should do this soon.

**Comment by teddyursa** [comment]
Yeah the app is so good now, scrolling past and marking them as actually read on your lemmy account would be great. wefwef has post hiding, but it's in app only, and not synced with your lemmy account. I'm sure Memmy will get there!

**Comment by gkasdorf** [comment]
@teddyursa kt just opened up a branch for this 😎

**Comment by teddyursa** [comment]
I'm not clued into github culture or what any dev things mean, but i'll take that as a big positive. Awesome. Congrats on the iOS release btw. o7

**Comment by sgriff96** [comment]
@teddyursa it means we're working on it actively :)

**Comment by dsl101** [comment]
> @teddyursa kt just opened up a branch for this 😎

I'm hoping you'll consider integrating [something like this](https://github.com/onderonur/react-intersection-observer-hook) with an option for 'mark read on scroll'. I think a combination from the last example there of `isVisible === false && wasEverVisible === true` should work. I've used IntersectionObserver in a Vue app to this effect, and it works well. 

Regarding the implementation, would the filter be done 'at refresh' rather than 'live'? So that you can still scroll back up to 'read' posts rather than have them immediately vanish when navigating back from a post to the feed?

**Comment by graham-pyett** [comment]
IMO on refresh is better (that’s how Apollo did it) so if you accidentally swipe back to the feed you can still get back in to where you were
