### ISSUE TITLE
[MEM-66] [BUG] Unable to access profile tab

### ISSUE THREAD

**Issue by GuillaumeLagrange** [Memmy-App/memmy#168]
**Describe the bug**
In the profile tab, I only see the message "that content or community was not found" and cannot access my profile.

**To Reproduce**

1. Go to profile tab

**Expected behavior**
A profile page for my logged in account.

**Screenshots**

![](https://uploads.linear.app/7655b776-38c4-4273-b069-78045fe3cd9c/e15e0189-03ae-4fd9-9f51-5477df22bda1/1b652ea2-257c-45b4-b58e-5ed84c370f46)

**Smartphone (please complete the following information):**

* Device: iPhone CS
* OS: iOS 16.5.1
* Version 0.0.1.72

**Logs:**
I would gladly provide logs but instructions do not work for me, and tapping "Email logs" does not work either :(

**Additional context**
My account has been created from lemmy.world, server settings is `lemmy.world`

Let me know if I can help and thanks for the exceptional work.

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-66](https://linear.app/memmyapp/issue/MEM-66/[bug]-unable-to-access-profile-tab)</sub>

**Comment by yrahul3910** [comment]
Huh, this is weird--the logs would've helped. Here's my research on this so far:

- The error originates in [ProfileScreen](https://github.com/gkasdorf/memmy/blob/main/components/screens/userProfile/ProfileScreen.tsx#L51-L53)
- That calls `useProfile`, where the most likely source of the error is the [call to `getPersonDetails`](https://github.com/gkasdorf/memmy/blob/main/components/hooks/profile/useProfile.ts#L67-L73).
- For the not found error specifically, it triggers when the error is `couldnt_find_that_username_or_email`.

My initial thoughts were that the JWT had expired, but I'm not entirely sure that's likely:
- Lemmy [creates a JWT](https://github.com/LemmyNet/lemmy/blob/main/crates/api/src/local_user/login.rs#L63-L74)
- That JWT [does not](https://github.com/LemmyNet/lemmy/blob/main/crates/utils/src/claims.rs#L27-L31), however, have an expiry claim.

@GuillaumeLagrange Can you log in to your Lemmy instance on the Web?

**Comment by GuillaumeLagrange** [comment]
I can log in on lemmy.world, but not on Mlem app, so it does look like there is something wrong with my account for the get personnal details route !

Here is the decoded payload my JWT in the local storage after I logged in on lemmy.world
```JSON
{
  "sub": 48542,
  "iss": "lemmy.world",
  "iat": 1687856270
}
```

Do you by chance have a curl/postman I can call with my token so I can give you the output of the getPersonnalDetails ?
Or could you point to an API doc that could allow me to perform the request on my end ?
Sorry I am completely new to Lemmy 😅 

We could also try and troubleshoot the logging situation so I can give you the logs directly 🚀

**Comment by gkasdorf** [comment]
Should probably do something to handle this better. I imagine you're not the only one who will use an email.

What I think we should do is on login, use the GetSite endpoint and grab the username from the...I think it's MyPerson, can't remember off the top of my head. Store the username in the account settings instead of the email.

Unfortunately user IDs are pretty worthless so I don't bother saving the user ID anywhere. Profile page uses name@instance to support both your own profile and other peoples'.

Thanks for pointing this out @GuillaumeLagrange!

**Comment by gkasdorf** [comment]
Bumping this, going to do this tomorrow.

**Comment by gkasdorf** [comment]
Ok so there were two issues here:

1. That you could have used an email to sign into the app with. I'm going to prefer using the username here because there could be some rather annoying issues with the current state of the API. If we try to make an additional request in the midst of authentication to retrieve your username, we might run into some issues. I'd rather just require a username.
2. There was actually an issue (I know a PR was submitted but I'm not sure if it has been merged yet) that it was possible for Lemmy to not differentiate between capitalized and lower case letters.

I think you had the former issue so I'd ask that you just continue to user usernames instead of emails, which I will start enforcing in the app. We can revisit that once instances start performing better (thankfully it looks like we are already trending in that direction!)
