### ISSUE TITLE
[MEM-96] Images are still not working

### ISSUE THREAD

**Issue by sc0ttwood** [Memmy-App/memmy#256]
As I read the update notes (Latest Update) and I saw images in the description I was like, thank god! And then I saw this, I don't think they are working correctly.

The second image is what it is meant to look like, I don't know if this is still in the works but if not, I'm just letting you know.

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/b726d394-bfee-4954-b812-7a7b9eec7347/1a20f286-0904-41d3-a644-146abffad364)

[Source image](https://github.com/gkasdorf/memmy/assets/138073160/db726c01-90a7-4e59-a5ba-07b2e3eb2eff)

![](https://uploads.linear.app/b97cc266-81c5-481a-af57-8318b58798fa/09e97689-5bc8-46cd-b5fe-6ae7e9fa4136/22546f20-8260-42bd-bf50-e0f3da4f8c1d)

[Source image](https://github.com/gkasdorf/memmy/assets/138073160/84e093d0-e512-4768-812c-00c88003f739)

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-96](https://linear.app/memmyios/issue/MEM-96/images-are-still-not-working)</sub>

**Comment by Taxxor90** [comment]
I posted the same behaviour on another issue where images aren't shown in the post like they are in the browser and also every other app so far.

The answer there was that they are not going to do that.
https://github.com/Memmy-App/memmy/issues/227#issuecomment-1616812169

Which seems odd to me because it completely breaks posts that are structured in blocks of text acompanied by images inbetween or like in your example just a simple list with added images. 

Using Memmy, you don't even see that there should be an image in these spots, only a link to the images at the end of the post with no idea where they are described in the post.

Maybe they'll change their minds, I'm on wefwef to the time being

**Comment by sgriff96** [comment]
We are going to look into displaying a link to each embedded image in the correct place, something like "Press to view image".

**Comment by eoddc5** [comment]
@gkasdorf is this reproducible?

**Comment by Taxxor90** [comment]
This post could serve as another example
https://lemm.ee/post/934162

On browser it looks like this
![browser](https://github.com/Memmy-App/memmy/assets/45570250/2328c2ae-b967-4932-b608-8a76ab940b23)

It has one image at the end of the initial post and two more images at the end of the first edit.

Voyager shows it like this (pretty ugly way of showing the code snippet btw but it'S about the images here^^)
![voyager](https://github.com/Memmy-App/memmy/assets/45570250/ad306d62-e743-457a-8f9d-baff41f0382e)


And with Memmy I see this
![memmy](https://github.com/Memmy-App/memmy/assets/45570250/6b85a263-3426-4b01-9f25-f3fa0e7b0336)

So there is a link to an image, but it's at the end of the post and it's also just one of the 3 images (the first of them) when I open that link.

I can understand if you say you don't want to have every image shown in full size but in this example there should then still be 3 separate links to the 3 images and those links should be placed where the images were placed in the post.
Because even if I could see all 3 images in a gallery view when clicking that link at the bottom, I wouldn't know the context of those images.

**Comment by ebits21** [comment]
So I've been quite confused about this and just figured it was broken for awhile.

If it says 4 images I should be able to open the image and swipe through all 4. Anything different is very confusing.

At least thumbnails or links or something.

![image](https://github.com/Memmy-App/memmy/assets/19845100/e28bf2f6-6385-4856-b05d-80d3b72cb1e8)

Only one image available in main view?

![image](https://github.com/Memmy-App/memmy/assets/19845100/fa13e764-e20e-4176-8dc4-95a5ac1cd9c7)

I open the image and I can only see one? Can't swipe left/right? I can't even see the second image that was in feed view?

I get if there's some technical limitation but there must be a better way?

**Comment by sgriff96** [comment]
All images are rendered now. Still working on swiping between images.
