### ISSUE TITLE
Long press profile tab icon to quick switch accounts

### ISSUE THREAD

**Issue by RustedSwitch** [Memmy-App/memmy#313]
**Is your feature request related to a problem? Please describe.**
Switching between accounts was a common activity on Reddit. I imagine the same scenario will exist here. This method really speeds up the process.  

**Describe the solution you'd like**
Long tap the profile tab icon to pop up a dialog with a list of the user’s signed-in account profile names. Tapping an account name in the list switches to that account profile. 

**Describe alternatives you've considered**
If popping up a dialog is a lot of effort, an interim solution would be to make long pressing the profile tab icon a shortcut to the account profile selection screen. 

**Additional context**
N/a

**Comment by gkasdorf** [comment]
So this is fine and probably a good idea, but we need to handle this gracefully somehow. Unfortunately, you can't just change accounts whenever you want without a "reload" pretty much, as post IDs, comment IDs, and community IDs are not the same across instances. That's why I had it in the feed index.

Will try to think of something.

**Comment by sgriff96** [comment]
@gkasdorf i was just going to make it take you to the feed and refresh the feed due to this
