### ISSUE TITLE
Suggestion: community subscriber count

### ISSUE THREAD

**Issue by chowanana99** [Memmy-App/memmy#338]
**Describe the solution you'd like**
In the search tab for communities I would like to be able to see how many subscribers each community has.

**Comment by Hikiru** [comment]
This should be medium priority imo, it’s very important when there’s a bunch of different communities and I can’t tell which one to join without clicking every single one. It’s incredibly annoying, especially since it doesn’t seem to sort search results by subscriber count. Mlem handles this way better, in fact sometimes I have to open Mlem just to find a community to back to memmy to view it.

**Comment by sgriff96** [comment]
@Hikiru agreed gonna work on it now

**Comment by sgriff96** [comment]
![simulator_screenshot_38B18BAE-0D83-437B-8C68-168A4A96CB51](https://github.com/Memmy-App/memmy/assets/46509416/2dedb592-97f9-4e58-9241-eb893e4084c4)

Looks like this now

**Comment by Hikiru** [comment]
That was quick, thanks
