### ISSUE TITLE
Consolidate “Feed” and “Traverse” on Navbar with Back Gesture?

### ISSUE THREAD

**Issue by Corb3t** [Memmy-App/memmy#636]
### Discussed in https://github.com/Memmy-App/memmy/discussions/532

<div type='discussions-op-text'>

<sup>Originally posted by **Corb3t** July  9, 2023</sup>
I love the work that’s been done on Memmy so far, but one user flow I’m so accustomed to in other Reddit-like apps is the ability to swipe back in the Feed section to display all my communities, similar to what is shown in Traverse. 

This user flow was in Apollo, and in the official Reddit app - could this be added in Memmy? Doing so means you could remove the “Traverse” navbar item and instead add a “Settings”, which you’ll eventually need as your app gets more fleshed out. 

Do you guys have any interest in some front-end help? Not sure what collaborative tools you guys use,  but I do have some UI/UX experience and would be happy to help.</div>

**Comment by eoddc5** [comment]
we are working on something that will greatly improve the feed and traverse interactions. 

its in top secret mode, but its going to have you all salivating

**Comment by eoddc5** [comment]
feed and traverse will not be combined. they have to (and will) remain as separate entities

**Comment by Taxxor90** [comment]
At least with the 0.4 update, the two are now combined because you can only access traverse directly from feed so it's exactly like almost all other apps now.

Before you could freely switch between two feeds, and even between two opened posts of these feeds, with just one button and always return to where you left. 

Just one example:
Replying to a post on "all" and want to get info from a specific communities post?  
Tap "Traverse", go to that community, open the post there and get the info.
Tap "Feed" and you're exactly where you left and can continue  writing your comment.

That was a unique feature you wouldn't find on any other app so far.
In every other app you'd have to leave that post to open the subscription view, go to the community and then go back and search that post in the feed again.

This is now also what you have to do on Memmy too and the traverse button was moved to the top of the screen where its harder to reach and only available in feed view and its old position where you could access it from anywhere is replaced by a settings button which was absolutely fine sitting inside the profile view(where it still is, too) and which is way less frequently used.

I don't know which other improvements are planned for this, but that change was a step back in my opinion.

**Comment by eoddc5** [comment]
> ### Discussed in #532
> Originally posted by **Corb3t** July 9, 2023 I love the work that’s been done on Memmy so far, but one user flow I’m so accustomed to in other Reddit-like apps is the ability to swipe back in the Feed section to display all my communities, similar to what is shown in Traverse.
> 
> This user flow was in Apollo, and in the official Reddit app - could this be added in Memmy? Doing so means you could remove the “Traverse” navbar item and instead add a “Settings”, which you’ll eventually need as your app gets more fleshed out.
> 
> Do you guys have any interest in some front-end help? Not sure what collaborative tools you guys use, but I do have some UI/UX experience and would be happy to help.

@Corb3t this feature is completed now and should be available to play with

For the helping portion , are you on the discord channel? You can sync up with @gkasdorf and @sgriff96 for helping out there

Going to close this issue as completed

**Comment by gkasdorf** [comment]
@Taxxor90 What is this in reference to? Sorry I am lost.

We have discussed adding an additional, customizable button to bring up these communities quickly. It's a work in progress. If that is what you are wanting, it will be there sooner than later.

**Comment by Taxxor90** [comment]
OP wanted the Apollo like UX of only being able to access subscriptions by swiping from the feed view instead of it being a separate tab.

I said that I liked the separate traverse tab because of the reasons listed in the two posts above and that I hope that it doesn't get combined like in Apollo.

Then it was posted that the two won't be combined and will stay separate.

Yesterday when I saw that the newest update did combine the two as there was no longer was a separate traverse tab I stated this here because it didn't match what was said.

Now as I got a notification about the issue being closed, I see that the statement about not combining traverse and feed was deleted(at least I can't see it anymore) so what would you think about that?

If the future customizable button you mentioned brings back the functionality that I described in the post above, then it's all good and you can ignore this rant ^^

Although I'd liked that to be included before stripping away that functionality because right now I don't see any benefit in comparison to the way it was before.
