### ISSUE TITLE
Empty space at the bottom

### ISSUE THREAD

**Issue by phil-lipp** [Memmy-App/memmy#733]
**Describe the bug**
There's an empty space at the bottom, which wasn't there before.

**To Reproduce**
Open Memmy.

**Expected behavior**
No empty space. Or better space utilisation 

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/52623794/a5a65834-f459-419e-8a9e-e700a56f4f80)

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2nd Gen (2022) 
 - OS: iOS 16.6
 - Memmy Version: 0.4

**Comment by ammacdonald3** [comment]
Do you mean in the bottom navbar? If so, I seem to have the opposite experience with this release. The navbar feels too short/compressed, and I always feel like I'm going to accidentally hit the iOS app switch handle when touching the menu items. 

My photo may be misleading because it shows a rectangular bottom, while the actual iPhone is curved on either side. In real life though, it feels too short.

![image](https://github.com/Memmy-App/memmy/assets/28578004/85714e8a-c165-43ea-8c4b-1062ebc5bebf)

Here is a second screenshot showing that the navbar is significantly shorter than other apps, like Instagram and Amazon.

![image](https://github.com/Memmy-App/memmy/assets/28578004/b1a1169e-32b6-4d4e-b652-cf952a9a181e)

**Comment by gkasdorf** [comment]
I think this is moreso an issue of different screen heights. It *should* only be an issue on iPhone 8 or lower. I do agree that it feels a bit too small on newer devices, so I'll look to do a fix for both of these issues.

**Comment by eoddc5** [comment]
Yeah on newer phones the “blank space” is filled with the “swipe up bar”

![image](https://github.com/Memmy-App/memmy/assets/10222895/a504597e-d6bf-4f9e-8c8a-f0fb94c475c9)

**Comment by DrakeRichards** [comment]
I don’t know if this is related, but I found that the ellipsis on my cutoff user name spills into this blank space. You can see it best on the profile page, where there’s that little blue dot in the bottom-center of the page. Is it spilling over because that blank space is available, or is that blank space created because of the length of the string?

![IMG_8115](https://github.com/Memmy-App/memmy/assets/35073576/73f92b28-a882-4db7-b109-75a8806115ed)

Device: iPhone 8
OS: iOS 16.5.1
App version: 0.5 (5)
