### ISSUE TITLE
Ability to turn off the comment jump button

### ISSUE THREAD

**Issue by michikade** [Memmy-App/memmy#877]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

I would like there to be a toggle off for the new comment jump button.  It’s just not something I use and it takes up screen space being there while I’m trying to read comments.  It also sits on top of the last comment’s upvote, downvote and comment buttons making it more difficult to interact with the bottom-most comment if someone does not use swipe commands.

Image is scrolled as far to the bottom as possible:

![IMG_4104](https://github.com/Memmy-App/memmy/assets/6156381/f168e27a-91b0-4046-988e-aba8f51e95f3)

### Solution

Add a toggle in “Appearance” to remove the button if the user would prefer it not on.

### Alternatives

N/A

**Comment by eoddc5** [comment]
@gkasdorf @sgriff96 off or auto hide options would be good 

I agree it’s a little intrusive

**Comment by theycallmebeez** [comment]
Might I also hijack this and suggest a couple things:

1. Positioning button up about half the height of the button (the verry bottom right corner is a "dead zone" for touch commands due to position. Up would help with UX/accessibility and overlap of the buttons as seen here.

2. Haptics so the user knows when clicking if it was clicked and should have advanced (working through some issues where clicking does not advance to next until I scroll a tad and click again).

3. Long-pressing the button goes to Previous Comment.

**Comment by urda** [comment]
I would like to completely remove this button, and arrived here when I found no option to.

**Comment by sgriff96** [comment]
> I would like to completely remove this button, and arrived here when I found no option to.

Yea it'll be added eventually

**Comment by gkasdorf** [comment]
@michikade @theycallmebeez @urda Done 👍
