### ISSUE TITLE
[Bug]: Default listing type in Feed persists as All

### ISSUE THREAD

**Issue by hungryca-t** [Memmy-App/memmy#917]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Listing type on Feed will default to All regardless of Default Listing Type (e.g. Local, Subscribed) chosen in Settings any time the app is fully closed then reopened. 

### Expected Behavior

Listing type should reflect Default Listing Type chosen in Settings. Instead, when the app is force closed then reopened, it will always default to All listing type on the feed. 

### Version

0.5.0 (13)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone SE 2nd Gen (2020)

**Comment by gkasdorf** [comment]
@hungryca-t I'm actually pretty confused by this one, but I know you are not the only one affected. I've made a change but I don't think it would actually resolve the issue...give it a day for new version to be released and let me know if it isn't fixed by @'ing me. We will revisit this if it isn't resolved.

**Comment by hungryca-t** [comment]
@gkasdorf unfortunately the issue is not resolved.
